// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_lsZuQgGjpMsnQy4Jd6onbHbENO4AqA',
    appId: '1:287194483321:web:3c266e650d1cc7e95562a8',
    messagingSenderId: '287194483321',
    projectId: 'fir-lab-mp',
    authDomain: 'fir-lab-mp.firebaseapp.com',
    storageBucket: 'fir-lab-mp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE4iq88JpczH6-aTo4nJ5lOB3G9F-9dek',
    appId: '1:287194483321:android:41e806242bedcdc35562a8',
    messagingSenderId: '287194483321',
    projectId: 'fir-lab-mp',
    storageBucket: 'fir-lab-mp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYa9yiyzNe74lQdGancYR682Vbk3OQ1sc',
    appId: '1:287194483321:ios:9a12e04e2e384d695562a8',
    messagingSenderId: '287194483321',
    projectId: 'fir-lab-mp',
    storageBucket: 'fir-lab-mp.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYa9yiyzNe74lQdGancYR682Vbk3OQ1sc',
    appId: '1:287194483321:ios:9a12e04e2e384d695562a8',
    messagingSenderId: '287194483321',
    projectId: 'fir-lab-mp',
    storageBucket: 'fir-lab-mp.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn_lsZuQgGjpMsnQy4Jd6onbHbENO4AqA',
    appId: '1:287194483321:web:8e49cea14864d9155562a8',
    messagingSenderId: '287194483321',
    projectId: 'fir-lab-mp',
    authDomain: 'fir-lab-mp.firebaseapp.com',
    storageBucket: 'fir-lab-mp.firebasestorage.app',
  );
}
